export const products = [
  {
    id: 1,
    name: "Coffee Machine 1",
    price: 919.11,
    quantity: 1,
    image: "/assets/img/1.png",
  },
  {
    id: 2,
    name: "Coffee Machine 2",
    price: 1257.92,
    quantity: 1,
    image: "/assets/img/2.png",
  },
  {
    id: 3,
    name: "Coffee Machine 3",
    price: 1500.85,
    quantity: 1,
    image: "/assets/img/3.png",
  },
  {
    id: 4,
    name: "Coffee Machine 4",
    price: 1250.9,
    quantity: 1,
    image: "/assets/img/4.png",
  },
  {
    id: 5,
    name: "Coffee Machine 5",
    price: 1750.85,
    quantity: 1,
    image: "/assets/img/5.png",
  },
  {
    id: 6,
    name: "Coffee Machine 6",
    price: 3100.61,
    quantity: 1,
    image: "/assets/img/6.png",
  },
  {
    id: 7,
    name: "Coffee Machine 7",
    price: 1801.1,
    quantity: 1,
    image: "/assets/img/7.png",
  },
  {
    id: 8,
    name: "Coffee Machine 8",
    price: 1199.99,
    quantity: 1,
    image: "/assets/img/8.png",
  },
  {
    id: 9,
    name: "Coffee Machine 9",
    price: 2395.16,
    quantity: 1,
    image: "/assets/img/9.png",
  },
  {
    id: 10,
    name: "Coffee Machine 10",
    price: 1243.82,
    quantity: 1,
    image: "/assets/img/10.png",
  },
];
